ipynb-filters: [nbdev_filter]

project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "sage-data-client-nbdev"
  site-url: "https://seanshahkarami.github.io/sage-data-client-nbdev/"
  description: ""
  execute: 
    enabled: false
  twitter-card: true
  open-graph: true
  reader-mode: true
  repo-branch: main
  repo-url: "https://github.com/seanshahkarami/https://github.com/seanshahkarami/sage-data-client-nbdev/"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/seanshahkarami/https://github.com/seanshahkarami/sage-data-client-nbdev/"
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
