# AUTOGENERATED! DO NOT EDIT! File to edit: ../core.ipynb.

# %% auto 0
__all__ = ['query', 'load']

# %% ../core.ipynb 3
def query(start): return "wow"

# %% ../core.ipynb 4
def load(path): return "loaded the data!"
