# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_core.ipynb.

# %% auto 0
__all__ = ['foo', 'query', 'load']

# %% ../00_core.ipynb 3
def foo(): pass

# %% ../00_core.ipynb 4
def query(start): return "wow"

# %% ../00_core.ipynb 5
def load(path): return "loaded the data!"
